# Generated by Django 6.0.5 on 2026-06-17 20:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def approve_existing_users(apps, schema_editor):
    """Grandfather in accounts that existed before the whitelist.

    They were already usable (active), so mark them approved instead of leaving
    them ``pending`` — otherwise the new login gate would lock them all out.
    """
    User = apps.get_model('accounts', 'User')
    User.objects.filter(is_active=True).update(
        approval_status='approved',
        approval_decided_at=django.utils.timezone.now(),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval_decided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entschieden am'),
        ),
        migrations.AddField(
            model_name='user',
            name='approval_requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registriert am'),
        ),
        migrations.AddField(
            model_name='user',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Wartet auf Freigabe'), ('approved', 'Freigegeben'), ('rejected', 'Abgelehnt')], db_index=True, default='pending', max_length=10, verbose_name='Freigabestatus'),
        ),
        migrations.AddField(
            model_name='user',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_decisions', to=settings.AUTH_USER_MODEL, verbose_name='Entschieden von'),
        ),
        migrations.RunPython(approve_existing_users, migrations.RunPython.noop),
    ]
