# Generated by Django 6.0.5 on 2026-06-16 19:54

import Collection_Management_System.models
import django.core.serializers.json
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CollectionShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view', 'Nur ansehen'), ('edit', 'Bearbeiten')], default='view', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80, verbose_name='Schlüssel')),
                ('label', models.CharField(max_length=150, verbose_name='Bezeichnung')),
                ('field_type', models.CharField(choices=[('text', 'Text (kurz)'), ('textarea', 'Text (lang)'), ('number', 'Ganzzahl'), ('decimal', 'Dezimalzahl'), ('price', 'Preis / Währung'), ('boolean', 'Ja / Nein'), ('date', 'Datum'), ('year', 'Jahr'), ('time', 'Uhrzeit'), ('datetime', 'Datum & Uhrzeit'), ('choice', 'Auswahl (eine)'), ('multichoice', 'Auswahl (mehrere)'), ('isbn', 'ISBN'), ('barcode', 'Barcode / EAN'), ('url', 'Link (URL)'), ('email', 'E-Mail'), ('image', 'Bild'), ('file', 'Datei')], default='text', max_length=20, verbose_name='Typ')),
                ('help_text', models.CharField(blank=True, max_length=300, verbose_name='Hilfetext')),
                ('required', models.BooleanField(default=False, verbose_name='Pflichtfeld')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_system', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('values', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_key', models.SlugField(max_length=80)),
                ('file', models.FileField(upload_to=Collection_Management_System.models.item_asset_path)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
