# Generated by Django 6.0.5 on 2026-06-16 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Collection_Management_System', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectionshare',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='Collection_Management_System.collection'),
        ),
        migrations.AddField(
            model_name='collectionshare',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fielddefinition',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='Collection_Management_System.collection'),
        ),
        migrations.AddField(
            model_name='item',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Collection_Management_System.collection'),
        ),
        migrations.AddField(
            model_name='item',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemasset',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='Collection_Management_System.item'),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_types', to='Collection_Management_System.collection'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='Collection_Management_System.itemtype'),
        ),
        migrations.AddField(
            model_name='fielddefinition',
            name='required_for_types',
            field=models.ManyToManyField(blank=True, related_name='required_fields', to='Collection_Management_System.itemtype'),
        ),
        migrations.AddConstraint(
            model_name='collectionshare',
            constraint=models.UniqueConstraint(fields=('collection', 'user'), name='unique_collection_share'),
        ),
        migrations.AddConstraint(
            model_name='itemtype',
            constraint=models.UniqueConstraint(fields=('collection', 'name'), name='unique_itemtype_per_collection'),
        ),
        migrations.AddConstraint(
            model_name='fielddefinition',
            constraint=models.UniqueConstraint(fields=('collection', 'key'), name='unique_field_key_per_collection'),
        ),
    ]
