# Generated by Django 6.0.5 on 2026-06-16 20:03

import Collection_Management_System.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection_Management_System', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemasset',
            name='file',
            field=models.FileField(max_length=255, upload_to=Collection_Management_System.models.item_asset_path),
        ),
    ]
