# Generated by Django 6.0.5 on 2026-06-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection_Management_System', '0003_alter_itemasset_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='lookup_provider',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Externe Datenbank'),
        ),
    ]
