# Generated by Django 6.0.5 on 2026-07-05 16:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection_Management_System', '0004_collection_lookup_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('borrower', models.CharField(max_length=120, verbose_name='Verliehen an')),
                ('lent_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Verliehen am')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Notiz')),
                ('returned_at', models.DateField(blank=True, null=True, verbose_name='Zurückgegeben am')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='Collection_Management_System.item')),
            ],
            options={
                'ordering': ['-lent_at'],
            },
        ),
    ]
