# Generated by Django 6.0.5 on 2026-07-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection_Management_System', '0005_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='due_at',
            field=models.DateField(blank=True, null=True, verbose_name='Rückgabe bis'),
        ),
    ]
