# Generated by Django 6.0.5 on 2026-07-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection_Management_System', '0006_loan_due_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='Schlüssel')),
                ('value', models.JSONField(blank=True, null=True, verbose_name='Wert')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Systemeinstellung',
                'verbose_name_plural': 'Systemeinstellungen',
                'ordering': ['key'],
            },
        ),
    ]
