# Generated by Django 6.0.5 on 2026-07-06 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection_Management_System', '0008_sitesetting_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, verbose_name='Schlüssel')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='Alter Wert')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='Neuer Wert')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Geändert am')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Geändert von')),
            ],
            options={
                'verbose_name': 'Einstellungsänderung',
                'verbose_name_plural': 'Einstellungsänderungen',
                'ordering': ['-changed_at'],
            },
        ),
    ]
