# Generated by Django 6.0.5 on 2026-07-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection_Management_System', '0009_settingchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Gelöscht am'),
        ),
        migrations.AddField(
            model_name='loan',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Erinnerung gesendet am'),
        ),
    ]
