# Generated by Django 6.0.5 on 2026-07-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection_Management_System', '0010_item_deleted_at_loan_reminder_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='lookup_provider',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Schwerpunkt'),
        ),
    ]
