# Generated by Django 6.0.5 on 2026-07-18 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection_Management_System', '0011_alter_collection_lookup_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('querystring', models.TextField(blank=True, verbose_name='Filter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to='Collection_Management_System.collection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gespeicherte Ansicht',
                'verbose_name_plural': 'Gespeicherte Ansichten',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('collection', 'name'), name='unique_saved_view_per_collection')],
            },
        ),
    ]
