# Generated by Django 6.0.5 on 2026-07-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection_Management_System', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='borrower_contact',
            field=models.CharField(blank=True, max_length=300, verbose_name='Kontakt / Anschrift'),
        ),
    ]
